-- Esquema completo del inventario en Postgres.
--
-- Sustituye a db/migrations/001-004 (dialecto SQLite) y al bloque
-- CREATE TABLE IF NOT EXISTS que server.js ejecutaba al arrancar. Ese bloque
-- existía porque el .db3 versionado iba por detrás de sus migraciones; con un
-- esquema aplicado una sola vez, ese problema desaparece y con él la trampa de
-- tener la misma definición escrita dos veces.
--
-- Las fechas son `text` con ISO-8601 en UTC, no `timestamptz`: no hay ni una
-- comparación de fecha en SQL — todas se hacen con Date.parse en JavaScript —
-- así que estas columnas son almacenamiento puro.
--
-- `activo` es integer (0/1) y no boolean porque el frontend lee
-- `Number(item.activo) === 1`. Cambiarlo obligaría a tocar public/.

CREATE TABLE areas (
  id_area integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre  text NOT NULL UNIQUE
);

CREATE TABLE productos (
  id_producto integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      text NOT NULL,
  marca       text,
  descripcion text,
  cantidad    integer NOT NULL DEFAULT 0,
  activo      integer NOT NULL DEFAULT 1,
  id_area     integer REFERENCES areas(id_area)
);

CREATE TABLE ordenes (
  id_orden    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creada_en   text NOT NULL,
  evento      text,
  responsable text
);

CREATE TABLE orden_lineas (
  id_linea    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden    integer NOT NULL REFERENCES ordenes(id_orden),
  -- SIN clave foránea a productos, y es la ÚNICA del esquema que no la lleva.
  -- En SQLite las REFERENCES eran decorativas (no hay PRAGMA foreign_keys), y
  -- el diseño depende de eso: DELETE /api/productos/:id es una operación real
  -- de superadmin, y las líneas huérfanas que deja son parte del modelo — la
  -- orden de marzo debe seguir diciendo qué salió aunque el producto ya no
  -- exista. La devolución trata ese caso a mano. Declarar la FK haría que
  -- borrar un producto fallara con 23503, convirtiendo una decisión de
  -- producto en un error de base de datos.
  id_producto integer NOT NULL,
  nombre      text NOT NULL,
  cantidad    integer NOT NULL
);

CREATE INDEX idx_orden_lineas_orden ON orden_lineas(id_orden);

CREATE TABLE devoluciones (
  id_devolucion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- El UNIQUE es la pieza importante, no un adorno del índice: hace de "una
  -- orden se devuelve una sola vez" una garantía de la base y no un if.
  id_orden      integer NOT NULL UNIQUE REFERENCES ordenes(id_orden),
  recibida_en   text NOT NULL,
  recibida_por  text
);

-- Los roles y lo que cada uno puede hacer. Son DOS y no se crean desde ningún
-- sitio: se probó tener una pantalla que los creara y se retiró. Que aun así
-- sean una tabla y no el CHECK de dos valores que había antes es lo que permite
-- preguntar por el permiso —`'cuentas.gestionar' = ANY (permisos)`— en vez de
-- comparar contra la cadena 'superadmin', y eso es lo que hace el servidor.
--
-- `permisos` NO se valida aquí, y tampoco lo valida nadie más: NINGUNA ruta
-- escribe esta columna. Reajustar lo que un rol puede hacer es hoy un UPDATE a
-- mano contra la base. Un CHECK con la lista de permisos sería esa misma lista
-- escrita dos veces, con la copia de aquí envejeciendo sola.
CREATE TABLE roles (
  nombre      text PRIMARY KEY,
  descripcion text,
  permisos    text[] NOT NULL DEFAULT '{}',
  -- 1 = rol de sistema. Sólo lo lleva `superadmin`. Hoy ninguna ruta lo mira
  -- —no queda nada que editar ni borrar desde la web—, pero se queda porque es
  -- lo que distingue el rol que abre la gestión del que sólo opera el almacén,
  -- y porque quitarlo pediría un ALTER contra la base ya desplegada.
  semilla     integer NOT NULL DEFAULT 0
);

-- Los dos roles con los que nace el sistema. Van en el esquema y no en un
-- script aparte porque sin ellos la FK de `cuentas.rol` no deja crear ninguna
-- cuenta: son parte de la estructura, no datos de ejemplo.
--
-- `superadmin` lleva los tres permisos ESCRITOS, no un comodín. Un '*' haría
-- que cada permiso nuevo cayera solo en el rol más poderoso; así, añadir uno
-- obliga a decidir a quién dárselo.
--
-- `admin` va con la lista vacía a propósito: hace todo el almacén —ver el
-- inventario, editarlo, emitir órdenes, recibir devoluciones—, porque nada de
-- eso está detrás de un permiso. Lo que no hace es lo que hay aquí escrito.
INSERT INTO roles (nombre, descripcion, permisos, semilla) VALUES
  ('superadmin', 'Gestiona las cuentas, ve la bitácora de accesos y borra productos.',
   '{productos.eliminar,cuentas.gestionar,accesos.ver}', 1),
  ('admin', 'Operación diaria del almacén: inventario, órdenes y devoluciones.',
   '{}', 0);

CREATE TABLE cuentas (
  id_cuenta        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario          text NOT NULL,
  hash             text NOT NULL,
  rol              text NOT NULL REFERENCES roles(nombre),
  -- DORMIDAS desde el 2026-08-28: el segundo factor se retiró y nada las lee.
  -- No se borran a propósito (ver «Estado conocido» en CLAUDE.md).
  totp_secreto     text,
  totp_ultimo_paso integer,
  creada_en        text NOT NULL,
  activa           integer NOT NULL DEFAULT 1
);

-- Postgres no tiene COLLATE NOCASE. El índice funcional conserva la misma
-- garantía que daba SQLite: "Erick" y "erick" son la misma persona, y que el
-- UNIQUE lo impida es mejor que descubrirlo el día que existan las dos cuentas.
-- Las consultas por usuario deben ir con lower(usuario) = lower($1).
CREATE UNIQUE INDEX idx_cuentas_usuario ON cuentas (lower(usuario));

CREATE TABLE sesiones (
  id_sesion  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- El SHA-256 del token, nunca el token: llevarse la base no entrega ninguna
  -- sesión viva.
  hash_token text NOT NULL UNIQUE,
  id_cuenta  integer NOT NULL REFERENCES cuentas(id_cuenta),
  creada_en  text NOT NULL,
  vista_en   text NOT NULL,
  expira_en  text NOT NULL,
  ip         text,
  agente     text
);

CREATE INDEX idx_sesiones_cuenta ON sesiones(id_cuenta);

-- DORMIDA desde el 2026-08-28: era la salida de emergencia del segundo
-- factor, hoy retirado. No se borra a propósito (ver «Estado conocido» en
-- CLAUDE.md).
CREATE TABLE codigos_respaldo (
  id_codigo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cuenta integer NOT NULL REFERENCES cuentas(id_cuenta),
  hash      text NOT NULL,
  usado_en  text
);

CREATE INDEX idx_codigos_respaldo_cuenta ON codigos_respaldo(id_cuenta);

CREATE TABLE accesos (
  id_acceso   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ocurrido_en text NOT NULL,
  usuario     text,
  resultado   text NOT NULL,
  ip          text
);

CREATE INDEX idx_accesos_fecha ON accesos(ocurrido_en);

-- Retos de segundo factor pendientes: contraseña ya verificada, código todavía
-- no. Vivían en un Map de proceso, que en serverless significa que el paso 2
-- del login puede caer en una instancia que nunca vio el reto.
-- DORMIDA desde el 2026-08-28: el segundo factor se retiró y nada la usa. No
-- se borra a propósito (ver «Estado conocido» en CLAUDE.md).
CREATE TABLE retos_totp (
  reto      text PRIMARY KEY,
  id_cuenta integer NOT NULL REFERENCES cuentas(id_cuenta),
  expira_en text NOT NULL
);

-- Limitador de intentos. Guarda `ultimo_en` y NO el instante de desbloqueo ya
-- calculado, que es lo que guardaba el Map: así anotar un fallo es un solo
-- INSERT ... ON CONFLICT, y la espera se calcula al leer con esperaTras(fallos),
-- que es donde esa fórmula ya vive.
CREATE TABLE intentos_login (
  clave     text PRIMARY KEY,
  fallos    integer NOT NULL,
  ultimo_en text NOT NULL
);
